server:
  port: 8080
rabbitmq:
  name: mailQueue
  exchangeName: mailExchange
  mailRoutingKey: mailRoutingKey


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Cinema
    username: cinema
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secretKey: fYvFzTl5uYCVIeZCpLC3xPskvEo6QhEqKlD33mMrnVmlU5lIOIuZo7WxJL8hStjyZdmR8EwHiU7lUkl6BhDYFQ==
    accessTokenExpirationTime: 1209500000 # 1 hour
    #    accessTokenExpirationTime: 30000
    refreshTokenExpirationTime: 1209600000 # 2 weeks

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: tanthanh.060918@gmail.com
    password: zgcu qqpg bmyn jzjl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/v1/payment/vnpay-success
    tmn-code: GWI0ZEDX
    hash-secret: 7YUKJOWXRG4X8WM8SOB64VWUCHMI6DF6
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    version: 2.1.0
    command: pay
    order-type: other
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

