server:
  port: 8080
rabbitmq:
  name: mailQueue
  exchangeName: mailExchange
  mailRoutingKey: mailRoutingKey


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Cinema
    username: cinema
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secretKey: fYvFzTl5uYCVIeZCpLC3xPskvEo6QhEqKlD33mMrnVmlU5lIOIuZo7WxJL8hStjyZdmR8EwHiU7lUkl6BhDYFQ==
    accessTokenExpirationTime: 3600000 # 1 hour
    #    accessTokenExpirationTime: 30000
    refreshTokenExpirationTime: 1209600000 # 2 weeks

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: tanthanh.060918@gmail.com
    password: zgcu qqpg bmyn jzjl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

