server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Cinema
    username: cinema
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secretKey: +I+kPBb1wOI0dqiUnes5T5eG6OQa0YJsLfKCuqXr1qQ=
    accessTokenExpirationTime: 3600000 # 1 hour
    #    accessTokenExpirationTime: 30000
    refreshTokenExpirationTime: 1209600000 # 2 weeks
